# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crm_ara_ekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from crm_basvurular import *
from crm_mulakat import *
from crm_mentor import *


class crm_ara_ekran(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 473)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 70, 231, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 220, 231, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 70, 231, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton.clicked.connect(self.go_to_crm_basvurular)
        self.pushButton_2.clicked.connect(self.go_to_crm_mulakat)
        self.pushButton_3.clicked.connect(self.go_to_crm_mentor)
        
    def go_to_crm_basvurular(self):
        self.crm_basvurular = crm_basvurular() 
        self.crm_basvurular.setupUi(MainWindow)
        MainWindow.show()
    
    def go_to_crm_mulakat(self):
        self.crm_mulakat = crm_mulakat() 
        self.crm_mulakat.setupUi(MainWindow)
        MainWindow.show()
    
    def go_to_crm_mentor(self):
        self.crm_mentor = crm_mentor() 
        self.crm_mentor.setupUi(MainWindow)
        MainWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tercihler"))
        self.pushButton.setText(_translate("MainWindow", "Basvurular "))
        self.pushButton_2.setText(_translate("MainWindow", "Mulakatlar "))
        self.pushButton_3.setText(_translate("MainWindow", "Mentor gorusmesi "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = crm_ara_ekran()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
